### ISSUE TITLE
Soundscapes from Youtube are not working

### ISSUE THREAD

**Issue by Fernando-Hurtado** [andrewmcgivery/obsidian-soundscapes#83]
Soundscapes from Youtube are not working. The radios or custom lists do not work, only listening to local music seems to work, so it may be the connection to youtube urls. It says error 153, related to the configuration of video reproductor (for radios), music not being reproduced. Similarly, the music is not being reproduced after hitting play  when it is a custom list. In this case, it says the video is not available (despite it is if you use a navigator).

**Comment by JohnWren** [comment]
> Soundscapes from Youtube are not working. The radios or custom lists do not work, only listening to local music seems to work, so it may be the connection to youtube urls. It says error 153, related to the configuration of video reproductor (for radios), music not being reproduced. Similarly, the music is not being reproduced after hitting play when it is a custom list. In this case, it says the video is not available (despite it is if you use a navigator).

It's working now!
Fixed by Obsidian in the v1.10.3 update

**Comment by fernando-hurtado-ctic** [comment]
> > Soundscapes from Youtube are not working. The radios or custom lists do not work, only listening to local music seems to work, so it may be the connection to youtube urls. It says error 153, related to the configuration of video reproductor (for radios), music not being reproduced. Similarly, the music is not being reproduced after hitting play when it is a custom list. In this case, it says the video is not available (despite it is if you use a navigator).
> 
> It's working now! Fixed by Obsidian in the v1.10.3 update

Most of it works, custom lists (not local music, I mean the custom lists from youtube) still do not work, but great at least to have the radios back.

**Comment by JohnWren** [comment]
> > > Soundscapes from Youtube are not working. The radios or custom lists do not work, only listening to local music seems to work, so it may be the connection to youtube urls. It says error 153, related to the configuration of video reproductor (for radios), music not being reproduced. Similarly, the music is not being reproduced after hitting play when it is a custom list. In this case, it says the video is not available (despite it is if you use a navigator).
> > 
> > 
> > It's working now! Fixed by Obsidian in the v1.10.3 update
> 
> Most of it works, custom lists (not local music, I mean the custom lists from youtube) still do not work, but great at least to have the radios back.

Everything is working for me: 
—Presets
—Custom sounscapes and 
—My Music
